# Generated by Django 5.1.4 on 2024-12-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_remove_building_building_outline'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='building',
            field=models.ManyToManyField(related_name='tenants', to='buildings.building'),
        ),
    ]
