# Generated by Django 5.1.4 on 2025-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_rename_building_xy_building_building'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='building',
        ),
        migrations.AddField(
            model_name='profile',
            name='buildings',
            field=models.ManyToManyField(related_name='profile', through='users.UserBuilding', to='buildings.building'),
        ),
    ]
