# Generated by Django 5.1.4 on 2024-12-21 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, null=True)),
                ('county', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_details', models.CharField(max_length=255)),
                ('occupancy', models.BooleanField()),
                ('building_outline', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=21037)),
                ('building_xy', django.contrib.gis.db.models.fields.PointField(srid=21037)),
            ],
            options={
                'db_table': 'building',
            },
        ),
    ]
