# Generated by Django 5.1.4 on 2025-01-02 17:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_str', models.CharField(max_length=50)),
                ('comment', models.CharField(default=None, max_length=255, null=True)),
                ('county', models.CharField(default=None, max_length=255, null=True)),
                ('district', models.CharField(default=None, max_length=255, null=True)),
                ('rent', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('payment_details', models.CharField(default=None, max_length=255, null=True)),
                ('occupancy', models.BooleanField(default=False)),
                ('building_xy', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
    ]
