# Generated by Django 5.1.4 on 2025-01-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='coordinate_str',
        ),
    ]
