# Generated by Django 5.1.4 on 2025-01-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_remove_building_coordinate_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='building_xy',
            new_name='building',
        ),
    ]
