# Generated by Django 5.1.4 on 2024-12-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_remove_building_building_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='coordinate_str',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
