# Generated by Django 5.1.4 on 2025-04-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_rename_building_xy_building_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='comment',
        ),
    ]
